[package]
name = "client"
version = "0.1.0"
authors = ["Mark Mansi <markm@cs.wisc.edu>", "Akhil Guliani <guliani@cs.wisc.edu>"]

[dependencies]
libc = "0.2"
time = "0.1.38"
thrift = "0.0.4"
zippyrpc = { path = "../protocol" }
clap = "2.26"
try_from = "0.2.2"
fuse = "0.3"
