[package]
name = "zippyrpc"
version = "0.1.0"
authors = ["Mark Mansi <markm@cs.wisc.edu>"]
build = "src/build.rs"
exclude = ["src/zippynfs.rs"]

[lib]
path = "src/zippynfs.rs"

[dependencies]
thrift = "0.0.4"
ordered-float = "0.3.0"
try_from = "0.2.0"
